// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBout() {
  return window['go']['main']['App']['CancelBout']();
}

export function GetLog() {
  return window['go']['main']['App']['GetLog']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Review(arg1) {
  return window['go']['main']['App']['Review'](arg1);
}

export function SetBoutMinutes(arg1) {
  return window['go']['main']['App']['SetBoutMinutes'](arg1);
}

export function SetOutcome(arg1) {
  return window['go']['main']['App']['SetOutcome'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartBout() {
  return window['go']['main']['App']['StartBout']();
}
