// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBout():Promise<string>;

export function GetLog():Promise<Array<Record<string, any>>>;

export function GetSessions():Promise<Array<Record<string, any>>>;

export function GetStats():Promise<Record<string, any>>;

export function GetStatus():Promise<Record<string, any>>;

export function Review(arg1:string):Promise<string>;

export function SetBoutMinutes(arg1:number):Promise<void>;

export function SetOutcome(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartBout():Promise<string>;
